NumPy for AI - Mini Project Assignment

In [1]:
import numpy as np

In [2]:
# Dataset of 10 students
# Math, Science, English, Computer, Result

data = np.array([
    [78, 85, 80, 90, 1],
    [45, 50, 40, 55, 0],
    [88, 92, 85, 95, 1],
    [60, 70, 65, 75, 1],
    [30, 35, 25, 40, 0],
    [95, 90, 93, 97, 1],
    [55, 58, 60, 62, 1],
    [40, 45, 42, 38, 0],
    [82, 78, 88, 84, 1],
    [48, 52, 50, 46, 0]
])

print("Dataset:\n")
print(data)

Dataset:

[[78 85 80 90  1]
 [45 50 40 55  0]
 [88 92 85 95  1]
 [60 70 65 75  1]
 [30 35 25 40  0]
 [95 90 93 97  1]
 [55 58 60 62  1]
 [40 45 42 38  0]
 [82 78 88 84  1]
 [48 52 50 46  0]]


In [3]:
# Features
X = data[:, 0:4]

# Labels
y = data[:, 4]

print("Features (X):\n")
print(X)

print("\nLabels (y):\n")
print(y)

Features (X):

[[78 85 80 90]
 [45 50 40 55]
 [88 92 85 95]
 [60 70 65 75]
 [30 35 25 40]
 [95 90 93 97]
 [55 58 60 62]
 [40 45 42 38]
 [82 78 88 84]
 [48 52 50 46]]

Labels (y):

[1 0 1 1 0 1 1 0 1 0]


In [4]:
average_marks = np.mean(X)
maximum_marks = np.max(X)
minimum_marks = np.min(X)

print("Average Marks:", average_marks)
print("Maximum Marks:", maximum_marks)
print("Minimum Marks:", minimum_marks)

Average Marks: 64.65
Maximum Marks: 97
Minimum Marks: 25


In [5]:
passed_students = np.sum(y == 1)
failed_students = np.sum(y == 0)

print("Passed Students:", passed_students)
print("Failed Students:", failed_students)

Passed Students: 6
Failed Students: 4


In [6]:
above_80 = X[X > 80]
below_50 = X[X < 50]

print("Marks Above 80:")
print(above_80)

print("\nMarks Below 50:")
print(below_50)

Marks Above 80:
[85 90 88 92 85 95 95 90 93 97 82 88 84]

Marks Below 50:
[45 40 30 35 25 40 40 45 42 38 48 46]


In [7]:
normalized_data = X / 100

print("Normalized Dataset:\n")
print(normalized_data)

Normalized Dataset:

[[0.78 0.85 0.8  0.9 ]
 [0.45 0.5  0.4  0.55]
 [0.88 0.92 0.85 0.95]
 [0.6  0.7  0.65 0.75]
 [0.3  0.35 0.25 0.4 ]
 [0.95 0.9  0.93 0.97]
 [0.55 0.58 0.6  0.62]
 [0.4  0.45 0.42 0.38]
 [0.82 0.78 0.88 0.84]
 [0.48 0.52 0.5  0.46]]


In [8]:
# average marks of each student
student_average = np.mean(X, axis=1)

# If average >= 50 → Pass (1)
# Else → Fail (0)

predictions = np.where(student_average >= 50, 1, 0)

print("Predictions:\n")
print(predictions)

Predictions:

[1 0 1 1 0 1 1 0 1 0]


In [9]:
accuracy = np.mean(predictions == y) * 100

print("Prediction Accuracy:", accuracy, "%")

Prediction Accuracy: 100.0 %
