NumPy for Artificial Intelligence

Task 1 — Creating Arrays

In [1]:
import numpy as np

# 1D array
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

# 2D array
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

# Zero array
zeros_arr = np.zeros((4,4))

# Ones array
ones_arr = np.ones((2,5))

# Display arrays
print("1D Array:")
print(arr1)

print("\n2D Array:")
print(arr2)

print("\nZeros Array:")
print(zeros_arr)

print("\nOnes Array:")
print(ones_arr)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Task 2 — Array Properties

In [2]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print("Array:")
print(arr)

print("\nShape:", arr.shape)
print("Total Elements:", arr.size)
print("Data Type:", arr.dtype)
print("Dimensions:", arr.ndim)

print("\nImportance of Shape in AI:")
print("Shape helps AI models understand rows and columns of data.")

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape: (3, 3)
Total Elements: 9
Data Type: int64
Dimensions: 2

Importance of Shape in AI:
Shape helps AI models understand rows and columns of data.


Task 3 — Indexing

In [3]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

print("Array:", arr)

print("First Element:", arr[0])
print("Last Element:", arr[-1])
print("Third Element:", arr[2])

print("Values Greater Than 30:")
print(arr[arr > 30])

Array: [10 20 30 40 50 60]
First Element: 10
Last Element: 60
Third Element: 30
Values Greater Than 30:
[40 50 60]


Task 4 — Slicing

In [4]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

print("Elements from index 1 to 4:")
print(arr[1:5])

print("\nReversed Array:")
print(arr[::-1])

print("\nAlternate Elements:")
print(arr[::2])

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("\nFirst Row:")
print(matrix[0])

print("\nSecond Column:")
print(matrix[:,1])

print("\nLast Two Rows:")
print(matrix[1:])

Elements from index 1 to 4:
[20 30 40 50]

Reversed Array:
[60 50 40 30 20 10]

Alternate Elements:
[10 30 50]

First Row:
[1 2 3]

Second Column:
[2 5 8]

Last Two Rows:
[[4 5 6]
 [7 8 9]]


Task 5 — Vectorization

In [5]:
import numpy as np

arr = np.array([1,2,3,4,5])

print("Original Array:")
print(arr)

print("\nMultiply by 5:")
print(arr * 5)

print("\nAdd 10:")
print(arr + 10)

print("\nSquare Elements:")
print(arr ** 2)

print("\nVectorization Importance in AI:")
print("Vectorization makes calculations faster without loops.")

Original Array:
[1 2 3 4 5]

Multiply by 5:
[ 5 10 15 20 25]

Add 10:
[11 12 13 14 15]

Square Elements:
[ 1  4  9 16 25]

Vectorization Importance in AI:
Vectorization makes calculations faster without loops.


Task 6 — Broadcasting

In [6]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])

print("Original Array:")
print(arr)

print("\nAdd 10:")
print(arr + 10)

print("\nMultiply by 2:")
print(arr * 2)

print("\nBroadcasting in ML:")
print("Broadcasting applies operations on arrays quickly.")

Original Array:
[[1 2 3]
 [4 5 6]]

Add 10:
[[11 12 13]
 [14 15 16]]

Multiply by 2:
[[ 2  4  6]
 [ 8 10 12]]

Broadcasting in ML:
Broadcasting applies operations on arrays quickly.


Task 7 — Matrix Addition and Subtraction

In [7]:
import numpy as np

A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print("Addition:")
print(A + B)

print("\nSubtraction:")
print(A - B)

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]


Task 8 — Matrix Multiplication

In [8]:
import numpy as np

A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print("Matrix Multiplication:")
print(np.dot(A,B))

print("\nTranspose of Matrix A:")
print(A.T)

print("\nNeural Networks:")
print("Neural networks use matrix multiplication for calculations.")

Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]

Neural Networks:
Neural networks use matrix multiplication for calculations.


Task 9 — Random Arrays

In [9]:
import numpy as np

arr = np.random.randint(1,101,(4,4))

print("Random Integer Array:")
print(arr)

decimal_arr = np.random.rand(4,4)

print("\nRandom Decimal Array:")
print(decimal_arr)

print("\nMaximum Value:", arr.max())
print("Minimum Value:", arr.min())
print("Average Value:", arr.mean())

print("\nImportance in AI:")
print("Random numbers help in training and testing AI models.")

Random Integer Array:
[[ 72  21  59  20]
 [ 87  70  51  75]
 [ 67 100  70  20]
 [ 15  52  42  88]]

Random Decimal Array:
[[0.82666237 0.48817268 0.126062   0.33265307]
 [0.45144603 0.81398002 0.36455539 0.11294857]
 [0.05982517 0.49747992 0.15578048 0.67391905]
 [0.82997332 0.88048566 0.72459491 0.39300444]]

Maximum Value: 100
Minimum Value: 15
Average Value: 56.8125

Importance in AI:
Random numbers help in training and testing AI models.


Task 10 — Student Marks Analysis

In [10]:
import numpy as np

marks = np.array([85,72,90,45,67,88,30,95,76,55])

print("Marks:")
print(marks)

print("\nAverage Marks:", marks.mean())
print("Highest Marks:", marks.max())
print("Lowest Marks:", marks.min())

print("\nStudents Above 80:")
print(marks[marks > 80])

print("\nFailed Students Below 50:")
print(marks[marks < 50])

Marks:
[85 72 90 45 67 88 30 95 76 55]

Average Marks: 70.3
Highest Marks: 95
Lowest Marks: 30

Students Above 80:
[85 90 88 95]

Failed Students Below 50:
[45 30]


Task 11 — Image Pixel Simulation

In [11]:
import numpy as np

image = np.random.randint(0,256,(5,5))

print("Image Pixels:")
print(image)

print("\nBrightest Pixel:", image.max())
print("Darkest Pixel:", image.min())
print("Shape of Image:", image.shape)

print("\nAI and Images:")
print("AI reads images as arrays of pixel values.")

Image Pixels:
[[ 97  11 240  23 147]
 [127  64 246  45  16]
 [161 220  82  88  25]
 [ 80 239   6  16  31]
 [ 42 103 189 243 205]]

Brightest Pixel: 246
Darkest Pixel: 6
Shape of Image: (5, 5)

AI and Images:
AI reads images as arrays of pixel values.


Task 12 — Data Normalization

In [12]:
import numpy as np

data = np.array([10,20,30,40,50])

normalized = (data - data.min()) / (data.max() - data.min())

print("Original Data:")
print(data)

print("\nNormalized Data:")
print(normalized)

print("\nImportance in AI:")
print("Normalization improves AI model accuracy and speed.")

Original Data:
[10 20 30 40 50]

Normalized Data:
[0.   0.25 0.5  0.75 1.  ]

Importance in AI:
Normalization improves AI model accuracy and speed.


Task 13 — Mini AI Dataset Task

In [13]:
import numpy as np

dataset = np.array([
    [25,50000,1],
    [30,60000,0],
    [22,45000,1],
    [35,70000,0]
])

print("Dataset:")
print(dataset)

# Input features
X = dataset[:,0:2]

# Output labels
y = dataset[:,2]

print("\nInput Features:")
print(X)

print("\nOutput Labels:")
print(y)

print("\nAverage Salary:", X[:,1].mean())
print("Highest Age:", X[:,0].max())
print("Dataset Shape:", dataset.shape)

Dataset:
[[   25 50000     1]
 [   30 60000     0]
 [   22 45000     1]
 [   35 70000     0]]

Input Features:
[[   25 50000]
 [   30 60000]
 [   22 45000]
 [   35 70000]]

Output Labels:
[1 0 1 0]

Average Salary: 56250.0
Highest Age: 35
Dataset Shape: (4, 3)
